-- MySQL Script generated by MySQL Workbench
-- 06/07/16 18:11:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spy2.0
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spy2.0
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spy2.0` DEFAULT CHARACTER SET utf8 ;
USE `spy2.0` ;

-- -----------------------------------------------------
-- Table `spy2.0`.`spy_commercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_commercial` (
  `commercial_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(75) NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`commercial_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_faculty` (
  `faculty_id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  `province` TINYTEXT NOT NULL,
  `city` TINYTEXT NOT NULL,
  `address` TINYTEXT NOT NULL,
  `coordinates` TINYTEXT NOT NULL,
  `postal_code` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`faculty_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_sector` (
  `sector_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sector_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_department` (
  `department_id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `state` INT NOT NULL DEFAULT 0,
  `CIF` VARCHAR(9) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `postal_code` INT(5) UNSIGNED NULL,
  `coordinates` VARCHAR(45) NULL,
  `photo` VARCHAR(100) NULL,
  `DISC` VARCHAR(18) NULL,
  `comment` MEDIUMTEXT NULL,
  `equipment` MEDIUMTEXT NULL,
  `commercial_id` INT NOT NULL,
  `faculty_id` INT NULL,
  `department_id` INT NULL,
  `category_id` INT NULL DEFAULT 1,
  `sector_id` INT NULL DEFAULT 1,
  PRIMARY KEY (`client_id`),
  INDEX `fk_spy_client_spy_commercial1_idx` (`commercial_id` ASC),
  INDEX `fk_spy_client_spy_faculty1_idx` (`faculty_id` ASC),
  INDEX `fk_spy_client_spy_category1_idx` (`category_id` ASC),
  INDEX `fk_spy_client_spy_sector1_idx` (`sector_id` ASC),
  INDEX `fk_spy_client_spy_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_spy_client_spy_commercial1`
    FOREIGN KEY (`commercial_id`)
    REFERENCES `spy2.0`.`spy_commercial` (`commercial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spy_client_spy_faculty1`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `spy2.0`.`spy_faculty` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spy_client_spy_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `spy2.0`.`spy_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spy_client_spy_sector1`
    FOREIGN KEY (`sector_id`)
    REFERENCES `spy2.0`.`spy_sector` (`sector_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spy_client_spy_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `spy2.0`.`spy_department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_taskT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_taskT` (
  `taskT_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `color` TINYTEXT NOT NULL,
  PRIMARY KEY (`taskT_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `state` TINYINT(1) NOT NULL DEFAULT 1,
  `subject` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `alert` DATETIME NULL,
  `report` VARCHAR(50) NULL,
  `client_id` INT NOT NULL,
  `taskT_id` INT NOT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `fk_tasks_spy_client1_idx` (`client_id` ASC),
  INDEX `fk_spy_task_spy_taskT1_idx` (`taskT_id` ASC),
  CONSTRAINT `fk_tasks_spy_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `spy2.0`.`spy_client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spy_task_spy_taskT1`
    FOREIGN KEY (`taskT_id`)
    REFERENCES `spy2.0`.`spy_taskT` (`taskT_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_note` (
  `note_id` INT NOT NULL AUTO_INCREMENT,
  `short_description` MEDIUMTEXT NOT NULL,
  `text` VARCHAR(45) NULL,
  `shared` TINYINT(1) NOT NULL DEFAULT 0,
  `date` DATETIME NOT NULL,
  `state` TINYINT(1) NULL DEFAULT 1,
  `commercial_id` INT NULL,
  PRIMARY KEY (`note_id`),
  INDEX `fk_spy_note_spy_commercial1_idx` (`commercial_id` ASC),
  CONSTRAINT `fk_spy_note_spy_commercial1`
    FOREIGN KEY (`commercial_id`)
    REFERENCES `spy2.0`.`spy_commercial` (`commercial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_guide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_guide` (
  `guide_id` INT NOT NULL AUTO_INCREMENT,
  `short_description` VARCHAR(45) NOT NULL,
  `text` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`guide_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_file` (
  `file_id` INT NOT NULL AUTO_INCREMENT,
  `short_description` VARCHAR(45) NOT NULL,
  `path` TINYTEXT NOT NULL,
  `shared` TINYINT(1) NOT NULL DEFAULT 0,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `commercial_id` INT NULL,
  `task_id` INT NULL,
  `guide_id` INT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `fk_spy_file_commercial1_idx` (`commercial_id` ASC),
  INDEX `fk_spy_file_spy_task1_idx` (`task_id` ASC),
  INDEX `fk_spy_file_spy_guide1_idx` (`guide_id` ASC),
  CONSTRAINT `fk_spy_file_commercial1`
    FOREIGN KEY (`commercial_id`)
    REFERENCES `spy2.0`.`spy_commercial` (`commercial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spy_file_spy_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `spy2.0`.`spy_task` (`task_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_spy_file_spy_guide1`
    FOREIGN KEY (`guide_id`)
    REFERENCES `spy2.0`.`spy_guide` (`guide_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_position` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spy2.0`.`spy_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spy2.0`.`spy_contact` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(9) NOT NULL,
  `mail` VARCHAR(120) NULL,
  `main` TINYINT(1) NOT NULL DEFAULT 0,
  `position_id` INT NULL DEFAULT 1,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `fk_spy_contact_spy_client1_idx` (`client_id` ASC),
  INDEX `fk_spy_contact_spy_position1_idx` (`position_id` ASC),
  CONSTRAINT `fk_spy_contact_spy_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `spy2.0`.`spy_client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spy_contact_spy_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `spy2.0`.`spy_position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
